env:
  CI: 1
  LANG: en_US.UTF-8
  LC_CTYPE: en_US.UTF-8

steps:
  - label: ':docker: Build docker image'
      agents:
        queue: docker-build
      plugins:
        docker-compose:
          build: app
          image-repository: rekrei/rekrei
          image-name: ${BUILDKITE_COMMIT:0:7}
          config:
            - docker-compose-build.yml
  - wait

  - label: ':rspec: Run specs'
    command: 'rspec --color specs'
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: "test"
